#!/usr/bin/env zsh
# Git aliases and shortcuts

# Basic Git commands
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log --oneline --graph'
alias gla='git log --oneline --graph --all'
alias gp='git push origin $(git branch --show-current)'
alias gpu='git push -u origin'
alias gpl='git pull'
alias gs='git status'
alias gst='git stash'
alias gstp='git stash pop'
alias gf='git fetch'
alias gr='git reset'
alias grh='git reset --hard'
alias grs='git reset --soft'
alias gb='git branch | fzf | xargs git checkout'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gm='git merge'
alias grb='git rebase'
alias grbi='git rebase -i'
alias grbc='git rebase --continue'
alias grba='git rebase --abort'

alias grso='git remote set-url origin'
alias glg='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias glog='git log --oneline --decorate --graph --all'
alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign -m "--wip-- [skip ci]"'
alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
